executable = /home/sbing/miniconda3/envs/timegan/bin/python3
arguments = "/home/sbing/thesis/git/TimeGAN/main_timegan.py --seed $(SEED) \
--features_path /work/sbing/datasets/mimiciii/processed/15_mins_all/include_static/X_6hrs_15min_34472_crystalloid_bolus_bin_proc.npz \
--labels_path /work/sbing/datasets/mimiciii/processed/15_mins_all/include_static/y_6hrs_15min_34472_crystalloid_bolus_bin_proc.npz \
--out_path /work/sbing/experiments/timegan/roc_per_class_eval/tgan_crys_ins_aug_$(SEED) \
--data_name mimic --hidden_dim 32 --batch_size 64 --num_layer 5 --epochs 100 --save True \
--group eval_insurance --subgroup 'timegan, crys, AUG' --run_name 'seed: $(SEED)'"

request_memory = 64000
request_cpus = 8
request_gpus = 1
getenv = True

requirements = CUDACapability>=6.0

error = /work/sbing/experiments/timegan/roc_per_class_eval/tgan_crys_ins_aug_$(SEED).err
output = /work/sbing/experiments/timegan/roc_per_class_eval/tgan_crys_ins_aug_$(SEED).out
log = /work/sbing/experiments/timegan/roc_per_class_eval/tgan_crys_ins_aug_$(SEED).log

queue 1 SEED in 1991, 3551, 6696, 0, 42
# queue 1 SEED in 0