executable = /home/sbing/miniconda3/envs/timegan/bin/python3
arguments = "/home/sbing/thesis/git/TimeGAN/main_timegan.py \
--features_path /work/sbing/datasets/mimiciii/processed/15_mins_all/refactor_test/X_6hrs_15min_17235_vent_bin_proc.npz \
--labels_path /work/sbing/datasets/mimiciii/processed/15_mins_all/refactor_test/y_6hrs_15min_17235_vent_bin_proc.npz \
--out_path /home/sbing/thesis/git/TimeGAN/experiments/timegan_hyperparams/less_pats/exp_$(Process) \
--data_name mimic --hidden_dim $(HID_DIM) --batch_size $(BS) --num_layer $(NUM_LAYER) --epochs 100 --save True --run_name 'timegan hyperparams combo $(Process)'"

request_memory = 64000
request_cpus = 8
request_gpus = 1
getenv = True

requirements = CUDACapability>=6.0

error = /home/sbing/thesis/git/TimeGAN/experiments/timegan_hyperparams/less_pats_$(Process).err
output = /home/sbing/thesis/git/TimeGAN/experiments/timegan_hyperparams/less_pats_$(Process).out
log = /home/sbing/thesis/git/TimeGAN/experiments/timegan_hyperparams/less_pats_$(Process).log

queue 1 HID_DIM, NUM_LAYER, BS from (
  32, 5, 64
  16, 1, 64
  32, 1, 128
  8, 1, 64
  24, 3, 32
  32, 5, 128
  32, 3, 64
  8, 5, 64
  8, 5, 32
  24, 5, 64
  24, 1, 32
  16, 1, 32
  24, 3, 128
  16, 3, 64
  16, 5, 128
  32, 1, 32
  32, 1, 64
  32, 3, 32
  32, 3, 128
  16, 5, 64
)